### ISSUE TITLE
Checking this project

### ISSUE THREAD

**Issue by fkolar** [ggranum/tangential#4]
Sorry that I am missusing the purpose of this, but I couldnot resist and had to ask you since this structure of the project is excellent. 

I started the same structure and then I ended up that I was not able to map relative paths just like @angular does it, so i search thrue the angular CLI adn I came across to your projects. 
- It builds
- IDE recognizes the packages
Amazing... 

I am sure you spend quite of time trying to figure out this. Let me ask you was there anything particular that you had to do ?

Besides changing paths inside tsconfig.json? I assume the other tsconfig.json inside lib and each individaul package.json is just for the gulp tasks. 

Thanks again and I appologize using issue to actually get some information!!!

I am on latest angular-cli which I need jsut for the demo/playgrounds, but for publising I want to use the same from material2.

-Fk

**Comment by ggranum** [comment]
As an addendum: Something to REALLY watch out for is accidentally using an '@project/this-module' import. Like what WebStorm/IntelliJ loves to auto-insert for you. 

If you are editing a component in a module - let's use admin-ui, for example - and you need to import something from within the admin-ui module, you MUST use relative URLs. If you do not, you will get a 'cannot resolve parameters for...' when you go to inject or use the thing. E.g. if you inject a value into a constructor, but used an @import, you get:
"Error: Can't resolve all parameters for TheClassName: ([object Object], ?)", where ? is the totally valid class that was accidentally imported with the wrong import style. 

I have burned far, far too much time on that particular oddity. 

I'm leaving this open for a bit in case you have some other questions.

**Comment by fkolar** [comment]
I expirienced this as well. If you are inside the module use direct and relative paths, otherwise Angular's compiler does not like it. Even if I look into angular master they are using the same. If inside module e.g. core, they do not refer to @angular/core, but they refer to it with relative paths. 

But too late ;-) I was updating my imports and testing different alternative back and forth like 4 times untill it passed thru .

But now it compiles ok. Even I still have some issue with `ng test`, but hopefully it iwll work after I finish full refactoring. 

Then its all about I guess to use Angular Materia 2, Gulp taska and bash scripts to make the build that will build it folder as @PROJECT
